### PR TITLE
Fix issue when binary framework name differs from Pod name

### PR DESCRIPTION
**Pull request by ichina**
replace all `+` and `-` characters with `_` in  non_binary_frameworks names

### CODE REVIEW

**Comment by ichina** [comment]
issue [here](https://github.com/Ruenzuo/cocoapods-amimono/issues/28)

**Comment by igor-makarov** [comment]
This is not the right way to do this, since it overlooks other cases where pod name differs from framework name, for example `leveldb-library` pod. I'm working on a pull request that covers all the cases by using the `product_name` property of the target.

**Comment by ichina** [comment]
Awesome!

**Comment by igor-makarov** [comment]
[#30](https://github.com/Ruenzuo/cocoapods-amimono/pull/30) fixes the issue in a more complete manner. Hope it helps!

**Comment by Ruenzuo** [comment]
@ichina closing this due https://github.com/Ruenzuo/cocoapods-amimono/pull/30, thank you for bringing up the discussion with https://github.com/Ruenzuo/cocoapods-amimono/issues/28.

**Pull request closed without merging**
